import React, { useEffect } from 'react';
import './Terms.css'

const TermsCondition = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, [])
    return (
        <div className='py-5 bg-darkblue' style={{ overflow: 'hidden' }}>
            <h2 className='text-center text-uppercase title-color pb-4'>Terms and conditions</h2>
            <div className='container primary'>
                <p>Purchase and License Terms of Sale Last Modified: Dec 22, 2022</p>
                <p>These S39 Global Purchase and License Terms of Sale (" Terms") are entered into by and between you (" you" and " your") and Digital Licensing, Inc. and its affiliates, including S39 Global (collectively " S39 Global ,"" we ," or " us"), and govern the purchase and use of hardware and software purchased from us through the Website and the use of the Portal provided by us. When you make a purchase on our Website, these terms are incorporated with the Website Terms and Conditions and collectively form the agreement between you and S39 Global. By accepting these Terms you further acknowledge and accept the Website Terms and Conditions. <br /> <br />
                PLEASE READ THESE TERMS CAREFULLY! THEY INCLUDE AN ARBITRATION PROVISION REQUIRING INDIVIDUAL ARBITRATION OF DISPUTES INSTEAD OF JURY TRIALS OR CLASS ACTIONS. By submitting your order or accepting or using products offered through the Website, you acknowledge that you agree to these Terms in their entirety as further provided in Section 1 below.
                </p>
                <h3 className='title-color'>Acceptance</h3>
                <p>BY CLICKING THE "I ACCEPT" BUTTON OR SIMILAR ATTESTATION WHEN SUCH OPTION IS MADE AVAILABLE TO YOU WHEN PURCHASING THE PRODUCT/HARDWARE AND/OR ANY LICENSE TO SOFTWARE, OR FOR APPLICABLE PROJECTS, OR OTHERWISE REGISTERING FOR THE PORTAL, YOU ACCEPT AND AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS EFFECTIVE AS OF THE DATE OF SUCH ACTION. YOU EXPRESSLY ACKNOWLEDGE AND REPRESENT THAT YOU HAVE CAREFULLY REVIEWED THESE TERMS AND CONDITIONS AND FULLY UNDERSTAND THE RISKS, COSTS, AND BENEFITS RELATED TO THE HARDWARE, SOFTWARE, AND ANY APPLICABLE PROJECTS. IF YOU ARE ENTERING INTO THESE TERMS AND CONDITIONS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THESE TERMS, IN WHICH CASE THE TERMS "YOU" OR "YOUR" SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT AGREE WITH ALL OF THE TERMS SET FORTH HEREIN, THEN YOU ARE EXPRESSLY PROHIBITED FROM MAKING ANY PURCHASE AND USING THE HARDWARE AND SOFTWAREYOU MUST DISCONTINUE ANY RESPECTIVE USE IMMEDIATELY. <br /> <br />
                The Products, Hardware, Software and Portal is intended for users who are at least eighteen (18) years old. Persons under the age of eighteen (18), as well any Disqualified Persons, are not permitted to use the Hardware, Software or Portal. <br /> <br />
                You are not authorized to use the Products, Hardware, Software or Portal if there are applicable legal restrictions in your country of residence that would make the participation in Projects illegal. It is your sole responsibility to ensure that your use of the Product, Hardware, Software, and/or Portal, including with respect to any applicable Project, is not prohibited, restricted, curtailed, hindered, impaired or otherwise adversely affected in any way by any applicable Law in your country of residence or domicile. In addition, you are not authorized to use the Product, Hardware, Software or Portal if you are: <br /> <br />
                a citizen, domiciled in, resident of, or physically present / located in Iran, North Korea, Cuba, Syria, China, Afghanistan, Central African Republic (the), Congo (the Democratic Republic of the), Libya, Mali, Somalia, Sudan, and Yemen (each an " Excluded Jurisdiction"). <br />
                where you are a corporate body: (i) which is incorporated in, or operates out of, an Excluded Jurisdiction, or (ii) which is under the control of one or more individuals who is/are citizens of, domiciled in, residents of, or physically present / located in, an Excluded Jurisdiction; <br />
                an individual or body corporate: (i) included in the consolidated list published by the United Nations Security Council of individuals or entities subject to measures imposed by the United Nations Security Council accessible at https://www.un.org/securitycouncil/content/un-sc-consolidated-list; or (ii) included in the United Nations Lists (UN Lists) or within the ambit of regulations relating to or implementing United Nations Security Council Resolutions listed by MAS and accessible by https://www.mas.gov.sg/regulation/anti-money-laundering/targeted-financial-sanctions/lists-of-designated-individuals-and-entities and https://www.mas.gov.sg/regulation/anti-money-laundering/targeted-financial-sanctions/regulations-for-targeted-financial-sanctions; or <br />
                an individual or corporate body who is otherwise prohibited or ineligible in any way, whether in full or in part, under any law applicable to such individual or corporate body from participating in any part of any Projects. <br /> <br />
                If you are not authorized to use the Hardware, Software, or Portal under this Section 1, you are deemed a " Disqualified Person" under these Terms. <br />
                Definitions. Any capitalized terms not otherwise defined in these Terms shall have the meaning set forth in the Website Terms and Conditions. <br />
                " Action" has the meaning set forth in Section 12.1. <br />
                " Customer Data" means information, data, and other content, in any form or medium, that is collected, downloaded, or otherwise received, directly or indirectly, from you by or through the Hardware, Software, and/or Portal. Customer Data does not included Resultant Data. <br />
                " Disputes" has the meaning set forth in Section 15. <br />
                " Disqualified Person" has the meaning set forth in Section 1 above. <br />
                " Documentation" means S39 Global ’s end-user documentation relating to the Product, Hardware, Software and/or Portal that S39 Global provides or makes available to you in any form or medium which describes the functionality, components, features, or requirements of the Software, including any aspect of the installation, configuration, integration, operation, or use of the Product, Hardware, Software and/or Portal with any applicable Project. <br />
                " Excluded Jurisdictions" has the meaning set forth in Section 1 above. <br />
                 " Fees" has the meaning set forth in Section 3.3 below. <br />
                 " Harmful Code"means any software, hardware, or other technology, device, or means, including any virus, worm, malware, or other malicious computer code, the purpose or effect of which is to (a) permit unauthorized access to, or to destroy, disrupt, disable, distort, or otherwise harm or impede in any manner any (i) computer, software, firmware, hardware, system, or network; or (ii) any application or function of any of the foregoing or the security, integrity, confidentiality, or use of any data processed thereby; or (b) prevent any customer of S39 Global from accessing or using the Portal, Hardware, Software, or any Project as intended by these Terms. <br />
                " Indemnitee" has the meaning set forth in Section 12.3. <br />
                " Indemnitor" has the meaning set forth in Section 12.3. <br />
                " Intellectual Property Rights" means any and all registered and unregistered rights granted, applied for, or otherwise now or hereafter in existence under or related to any patent, copyright, trademark, trade secret, database protection, or other intellectual property rights Laws, and all similar or equivalent rights or forms of protection, in any part of the world. <br />
                " JAMS" has the meaning set forth in Section 15. <br />
                 "Law(s)" means any statute, law, ordinance, regulation, rule, code, order, constitution, treaty, common law, judgment, decree, or other requirement of any federal, state, local, or foreign government or political subdivision thereof, or any arbitrator, court, or tribunal of competent jurisdiction. <br />
                " Losses" means any and all losses, damages, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including reasonable attorneys' fees and the costs of enforcing any right to indemnification hereunder and the cost of pursuing any insurance providers. <br />
                "Maintenance Release(s)" means any update, upgrade, release, or other adaptation or modification of the Software, including any updated Documentation, that S39 Global may provide to you from time to time, which may contain, among other things, error corrections, enhancements, improvements, or other changes to the user interface, functionality, compatibility, capabilities, performance, efficiency, or quality of the Software, but does not include any new version of the Software. <br />
                " Open Source Components" means any software component that is subject to any open source license agreement, including any software available under the GNU Affero General Public License (AGPL), GNU General Public License (GPL), GNU Lesser General Public License (LGPL), Mozilla Public License (MPL), Apache License, BSD licenses, or any other license that is approved by the Open Source Initiative. <br />
                " Open Source Licenses" has the meaning set forth in Section 4.2. <br />
                " Portal" has the meaning set forth in Section 7.1. <br />
                " Projects" partner projects compatible with the Software that are selectable by you to participate through the purchase of a license to such respective project, as provided on the Website. <br />
                " Resultant Data" means data and information related to your use of the Hardware, Software and/or Portal that is used by S39 Global in an aggregate and/or anonymized manner, including to compile statistical and performance information related to the provision and operation of the Hardware, Software and/or Portal. <br />
                " Software" means the executable, object code version of the software pre-loaded on the Hardware, and any Maintenance Releases provided to you pursuant to these Terms and which allow up to the selection of twenty (20) Projects to run on the Hardware and generate Tokens. <br />
                " Terms" has the meaning set forth in Section 14. <br />
                " Tokens" means the cryptocurrency generated as a result of the participation in any specific project utilizing the Software and Hardware in accordance with these Terms. <br />
                " Warranty Period" has the meaning set forth in Section 10.1 below. <br />

                </p>
                <h3 className='title-color'>Purchase Terms</h3>
                <p>
                Orders and Acceptance. You agree that any order to purchase Product, Hardware and any license to Software and respective Projects are an offer, under these Terms. All orders must be accepted by us or we will not be obligated to sell the Product, Hardware or Software licenses to you. We may choose not to accept orders at our sole discretion, even after we send you a confirmation email with your order number and details of your order. <br />
                Purchase Restrictions. The following purchase restrictions apply: <br />
                _ Hardware Purchase Restrictions _. Upon your initial purchase of the Software license, you will receive the necessary Hardware to run the Software at no additional charge. This right to free Hardware with the purchase of Software is limited to your first purchase only at a limit of one per customer. Any additional Hardware desired by you or otherwise required to run additional Projects licensed with the Software must be purchased at the then current Fee price (as further provided in Section 3.3 below). You may not obtain any additional Hardware for free under any circumstances. You agree that you will not create any secondary accounts, or use other third parties as a proxy to obtain any additional free Hardware. <br />
                _ Software and Underlying Project License Purchase Restrictions _. The price of the Software license is dependent upon the number of Projects you select and purchase a license to. Each Hardware device with the Software can run up to twenty (20) Projects. Please refer to Section 3.3 for more information about Fees and how to determine the current Fee price of any respective Project. If you purchase more than twenty (20) Projects, you will need to purchase additional Hardware as necessary to support the additional Projects exceeding the allotted twenty (20) Projects per device. <br />
                Payment Terms. We accept payment for Products, Hardware, Software and Project Licenses using the following Methods: <br />
                _ Cryptocurrency Payment _ – You may make payments using cryptocurrencies through our third-party payment processor Metamask. The cryptocurrencies accepted by Metamask are not controlled by the S39 Global . Payment of accepted cryptocurrencies will be at the rates equivalent to the comparative U.S. Dollar value of such cryptocurrency at the time of the purchase. <br />
                You represent and warrant that (a) the payment information (including any related digital wallet information for cryptocurrency transactions or credit card numbers you supply to us are true, correct and complete, (b) you are duly authorized to use such payment information to make a purchase, (c) where applicable, charges incurred by you will be honoured by your credit card company, and (d) you will pay charges incurred by you at the posted Fee prices, including shipping and handling charges and all applicable taxes, if any, incurred at the time of your order. The information collected by third-party payment processors, including Metamask. S39 Global is not responsible for the actions of any third-party payment processor. <br />
                Licenses; Security Measures Intellectual Property Rights <br />
                License Grant. Subject to and conditioned on your payment of the applicable Fees with respect to the Products, Hardware, Software and applicable Projects, and further conditioned upon the compliance with these Terms, S39 Global hereby grants to you a non-exclusive, non-sublicensable, and non-transferable license to use the Software and Documentation to run the applicable Projects you selected and paid Fees to participate in, on the purchased Hardware and solely in accordance with the requirements set forth in the Documentation. <br />
                Open Source Licenses. The Software includes Open Source Components licensed for use with the Software. Any use of the Open Source Components by you is governed by, and subject to, the terms and conditions of the applicable open source license(s). <br />
                Security Measures. The Hardware, Software, and Portal may contain technological measures designed to prevent unauthorized or illegal use. You acknowledges and agrees that S39 Global may use these technological measures and other lawful measures to verify your compliance with these Terms and enforce S39 Global rights, including all Intellectual Property Rights, in and to the Software and Portal. <br />
                License and Use Restrictions for the Portal and Software. Except as these Terms expressly permits, and subject to Section 4.2 with respect to Open Source Components, you shall not: <br />
                copy the Software or Portal, in whole or in part; <br />
                modify, correct, adapt, translate, enhance, or otherwise prepare derivative works or improvements of any Software or Portal; <br />
                rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Software or Portal to any third party; <br />
                reverse engineer, disassemble, decompile, decode, or adapt the Software or Portal, or otherwise attempt to derive or gain access to the source code of the Software or Portal, in whole or in part; <br />
                bypass or breach any security device or protection used for or contained in the Software, Portal, or Documentation; <br />
                remove, delete, efface, alter, obscure, translate, combine, supplement, or otherwise change any trademarks, terms of the Documentation, warranties, disclaimers, or Intellectual Property Rights, proprietary rights or other symbols, notices, marks, or serial numbers on or relating to any copy of the Software, Portal, or Documentation; <br />
                use the Software or Portal in any manner or for any purpose that infringes, misappropriates, or otherwise violates any Intellectual Property Right or other right of any person, or that violates any applicable Law; <br />
                use the Software or Portal for purposes of: (i) benchmarking or competitive analysis of the Software or Portal; (ii) developing, using, or providing a competing software product or service; or (iii) any other purpose that is to S39 Global detriment or commercial disadvantage; and <br />
                use the Software, Portal, or Documentation in any manner or for any purpose or application not expressly permitted under these Terms. <br />
                Intellectual Property Rights. You acknowledge that: <br />
                the Software, rights to use the Portal, and Documentation are licensed, not sold, to you by S39 Global and you do not have under or in connection with these Terms any ownership interest in or to the Software or Documentation, or in any related Intellectual Property Rights therein. <br />
                S39 Global and its applicable licensors are the sole and exclusive owners of all right, title, and interest in and to the Software, Portal, and Documentation, including all Intellectual Property Rights relating thereto, subject only to the rights of third parties in Open Source Components and the limited license granted to you under these Term; and <br />
                you hereby unconditionally and irrevocably assign to S39 Global or S39 Global designee, your entire right, title, and interest in and to any Intellectual Property Rights that you may now or hereafter have in or relating to the Software, Documentation, and Resultant Data (including any rights in derivative works or patent improvements), whether held or acquired by operation of Law, contract, assignment or otherwise. <br />
                No Implied Rights. Except for the limited rights and licenses expressly granted under these Terms, nothing in these Terms grants, by implication, waiver, estoppel or otherwise, to you or any third party, any Intellectual Property Rights or other right, title, or interest in or to any of the Software, Portal, or Documentation. <br />
                Maintenance Releases. During the Warranty Period, and at S39 Global 's sole discretion following the Warranty Period, S39 Global will provide you with all Maintenance Releases (including updated Documentation) that we may, in our sole discretion, make generally available to its licensees at no additional charge. All Maintenance Releases provided by S39 Global to you are deemed Software. You will install all Maintenance Releases as soon as practicable after receipt. You do not have any right hereunder to receive any new versions of the Software that S39 Global may, in its sole discretion, release from time to time. <br />
                Digital Wallet. The digital wallet used in the Software is an Open-Source Component. Such digital wallet has a public key and a private key. You will be provided the private key and will alone have access to such private key. S39 Global does not store your private key in any reasonably accessible manner and cannot help you retrieve your private key if you lose such private key. You have the sole responsibility to maintain, in your fully secure possession, the credentials for accessing your digital wallet, including the private key for your digital wallet. <br />

                </p>
                <h3 className='title-color'>S39 Global Portal.</h3>
                <p>
                Portal. Use of the Hardware and participation in any Projects further requires the creation and maintenance of an account for our S39 Global dashboard to keep track of respective Projects licensed, the performance of Projects, and other related information associated with your use of the Hardware and Software (such dashboard herein referred to as the " Portal"). S39 Global hereby grants you a non-exclusive, non-transferable right to access and use the Portal during the Term in accordance with the terms and conditions herein. Such use is limited to your internal use with your Hardware, Software and applicable Projects. <br />
                Changes to the Portal. S39 Global reserves the right, in its sole discretion, to make any changes to the Portal that it deems necessary or useful to: (a) maintain or enhance: (i) the quality or delivery of the Portal and its related services to its customers; or (ii) the Portal's cost efficiency or performance; or (b) to comply with applicable Law. <br />
                Portal Use Restrictions. Use restrictions of the Portal are set forth ins Section 4.4 above. <br />
                Portal Account. To make use of any purchased license, you will need to create an account, including providing a verifiable email address and creating a unique password. You are responsible for your account activity, including unauthorized activity. You must safeguard the confidentiality of your account credentials, including your username and password. If you become aware of unauthorized access to your account, you must change your password and notify us immediately. <br />
                Customer Data. The Portal, connected through your established account and connected Hardware, Software and associated Projects, will process Customer Data. As between you and S39 Global, you are and will remain the sole and exclusive owner of all right, title, and interest in and to all Customer Data, including all Intellectual Property Rights relating thereto, subject to the rights and permissions granted herein. You represent, warrant, and covenant to S39 Global that you own or otherwise have and will have the necessary rights and consents in and relating to the Customer Data so that, as received by S39 Global and processed in accordance with these Terms, they do not and will not infringe, misappropriate, or otherwise violate any Intellectual Property Rights, or any privacy or other rights of any third party or violate any applicable Law. You hereby irrevocably grant all such rights and permissions in or relating to Customer Data as necessary or useful to S39 Global to enforce these Terms and exercise S39 Global 's rights and perform S39 Global 's obligations hereunder. Any Customer Data collected or otherwise processed by S39 Global will be processed in accordance with S39 Global 's privacy policy s39global.com/privacy. <br />
                Shipment; Title and Risk of Loss <br />
                Shipment. We will arrange for shipment of the products to you. You will pay all shipping and handling charges specified during the ordering process. Shipping and handling charges are reimbursements for the costs we incur in the processing, handling, packing, shipping, and delivery of your order. <br />
                Title and Risk of Loss. Title and risk of loss passes to you upon our transfer of the products to the shipping carrier. Shipping and delivery dates are estimates only and cannot be guaranteed. We are not liable for any delays in shipments. <br />
                No Returns or Refunds. The Fees paid with respect to the Products, Hardware, Software, and any applicable Projects are non-refundable, and we do not accept any returns of Products, Hardware for any reason, except as otherwise may be required under applicable Law. <br />
                Limited Product and Hardware Warranty; Disclaimers. <br />
                Disclaimer Warranties. EXCEPT AS EXPRESSLY SET FORTH IN SECTION 10.1 ABOVE, ALL PRODUCTS,HARDWARE AND SOFTWARE OFFERED ON THE WEBSITE, INCLUDING THE PORTAL ARE PROVIDED "AS IS" WITHOUT ANY WARRANTY WHATSOEVER, INCLUDING, WITHOUT LIMITATION, ANY (A) WARRANTY OF MERCHANTABILITY; (B) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; OR (C) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER EXPRESS OR IMPLIED BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE. SOME JURISDICTIONS LIMIT OR DO NOT ALLOW THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES, IN WHICH CASE, THE DISCLAIMER IN THIS SECTION 10.3 MAY NOT APPLY TO YOU. S39 GLOBAL SHALL NOT BE LIABLE OR OTHERWISE RESPONSIBLE FOR ANY DATA LOSS RELATING TO ANY CUSTOMER DATA, AND SHALL HAVE NO OBLIGATION TO BACK-UP ANY SUCH CUSTOMER DATA. <br />
                PROJECT DISCLAIMER. S39 GLOBAL IS NOT AFFILIATED WITH, NOR DOES IT RECOMMEND ANY SPECIFIC PROJECT FOR YOU TO CHOOSE TO PARTICIPATE IN USING THE SOFTWARE. S39 GLOBAL SOFTWARE ALLOWS YOU TO ACT AS A MINER FOR ANY OF YOUR CHOSEN PROJECTS, BUT THE SUCCESS OF ANY SUCH PROJECT, UNDERLYING TRANSACTIONS, AND TOKENS GENERATED IS NOT CONTROLLED IN ANY WAY BY S39 GLOBAL. YOU AGREE THAT S39 GLOBAL SHALL NOT HAVE ANY RESPONSIBILITY OR LIABILITY FOR, ARISING OUT OF, RELATING TO, ASSOCIATED WITH OR RESULTING FROM YOUR PARTICIPATION IN ANY PROJECT. YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE LEGITIMACY AND AUTHENTICITY PROJECTS YOU PARTICIPATE IN USING THE SOFTWARE. <br />
                DIGITAL WALLET DISCLAIMER. S39 GLOBAL HAS NO CONTROL OVER YOUR DIGITAL WALLET AND CANNOT GUARANTEE THE SECURITY OF ANY SUCH DIGITAL WALLET. CONTINUED STORAGE OF ANY TOKENS OR OTHER DIGITAL ASSETS ON THE DIGITAL WALLET PROVIDED WITH THE HARDWARE OR ANY OTHER DIGITAL WALLET YOU MAY TRANSFER TOKENS OR DIGITAL ASSETS TO, IS DONE SO AT YOUR OWN RISK. IN THE EVENT OF ANY LOSS, HACK OR THEFT OF ANY TOKENS OR OTHER DIGITAL ASSETS FROM YOUR DIGITAL WALLET, YOU ACKNOWLEDGE AND AGREE THAT YOU SHALL HAVE NO RIGHT(S), CLAIM(S) OR CAUSES OF ACTION IN ANY WAY WHATSOEVER AGAINST S39 GLOBAL FOR SUCH LOSS, HACK OR THEFT OF ANY SUCH DIGITAL ASSET. <br />
                Inherent Risk of Cryptographic Systems. You hereby acknowledge and assume the risk of using the Hardware and Software with respect to Projects and the inherent risks of blockchain technologies and mining tokens, including: <br />
                Many market, technological and legal forces are outside the exclusive control of Management Company. Cryptocurrencies such as Tokens, blockchain technology, and other associated and related technologies are not exclusively controlled by S39 Global and adverse changes in market forces, including but not limited to, amendments to regulatory or intellectual property law, technological advancements, decreases in token or cryptocurrency or cryptographic token utility, social or economic reforms, the failure of commercial relationships, or the malfunction, breakdown or abandonment of the cryptocurrency protocols may affect the performance of any Project. <br />
                The application of blockchain technology is novel and untested and may contain inherent flaws or limitations. Blockchain is an emerging technology that offers new capabilities which are not fully proven in use. Risks associated with the blockchain technology could affect the performance of any Project, including the market for blockchain assets generally. <br />
                The success of any respective Project requires interest from a large number of validators and/or other network participants. The success of any applicable Project relies on a significant number of parties willing to act as validators and/or miners, supporters or other participants of the network. There is no guarantee however, that a sufficient number of individuals will continue participate in any respective Project. No one is contractually or legally obligated to continue to participate in any applicable Project and may cease participation if they determine that such participation is no longer profitable, if they are prevented from doing so by government or regulatory agencies, or for any other reason. If participants cease to continue supporting the a respective Project, such Project may be unable to function and the value of underlying Tokens may decline or decrease to zero. <br />
                Tokens are not insured. Tokens are not insured by any governmental or regulatory entity. In the event of loss, or the loss of the utility value of Tokens, you will have no recourse (and shall never have recourse against S39 Global in accordance with these Terms) unless you have obtained private insurance for such respective Tokens. <br />
                There is no guarantee that any Tokens will hold value or increase in value. Tokens and other cryptocurrencies are highly speculative, and any increase in value of respective Tokens is contingent upon numerous circumstances, many of which (including legal and regulatory conditions) are beyond S39 Global 's control. There is no assurance that any Token will increase in value, or that applicable Tokens will have any value or liquidity when you acquire them. <br />
                The tax treatment of the tokens is uncertain and there may be adverse tax consequences. The tax characterization of Tokens is uncertain, and holding Tokens may result in adverse tax consequences. <br />
                Regulatory Uncertainty. The regulatory regime governing blockchain technologies, cryptocurrency, and other crypto-based items is uncertain, and new regulations or policies may materially adversely affect the value of any Project and/or Tokens generated using the Hardware and Software. <br />
                Distributed Ledger Technology risk. There are risks associated with using Internet and distributed-ledger or other blockchain based products, including, but not limited to, the risk associated with hardware, software, and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to your digital wallet or account. <br />
                Third-Party Services. We do not control third-party services or products like the underlying blockchains that the respective Projects run on, the digital wallets, or other third-party products that you may be interacting with that may be integral to your ability to participate in Projects and generate and store Tokens. Such third parties may experience system outages or other technological events that disrupt your ability to participate in a respective Project during such disruption. <br />
                No Investment Advice. S39 Global is acting solely as a technology services provider and does not provide any investment, tax or other advisor services regarding Tokens, Projects, or otherwise. <br />
                Applicable Law. The use of the Hardware and Software to participate in applicable Projects are subject to all applicable Laws. S39 Global reserves the right to make changes to its policies, operational guides, procedures, and protocols, including any changes to Documentation and/or Software, as necessary to comply with Law. <br />
                Limitation of Liability. IN NO EVENT SHALL WE BE LIABLE TO YOU OR ANY THIRD PARTY FOR CONSEQUENTIAL, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR ENHANCED DAMAGES, LOST PROFITS OR REVENUES OR DIMINUTION IN VALUE, ARISING OUT OF, OR RELATING TO, AND/OR IN CONNECTION WITH ANY BREACH OF THESE TERMS, REGARDLESS OF (A) WHETHER SUCH DAMAGES WERE FORESEEABLE, (B) WHETHER OR NOT WE WERE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND (C) THE LEGAL OR EQUITABLE THEORY (CONTRACT, TORT OR OTHERWISE) UPON WHICH THE CLAIM IS BASED. OUR SOLE AND ENTIRE MAXIMUM LIABILITY AND YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY CAUSE WHATSOEVER, SHALL BE LIMITED TO THE ACTUAL AMOUNT PAID BY YOU FOR THE PRODUCTS AND SERVICES YOU HAVE ORDERED THROUGH OUR WEBSITE. <br />

                </p>
                <h3 className='title-color'> Indemnification</h3>
                <p>
                S39 Global Indemnification of You. S39 Global shall indemnify, defend, and hold you harmless from and against any and all Losses incurred by you resulting from any claim, action, cause of action, demand, lawsuit, arbitration, inquiry, audit, proceeding, litigation, citation, summons, subpoena, or investigation of any nature, civil, criminal, administrative, regulatory, or other, whether at law, in equity, or otherwise, (" Action") by a third party that the Software or Documentation, or any use of the Software or Documentation in accordance with these Terms, infringes or misappropriates such third party's US Intellectual Property Rights. This Section 12.1 does not apply to the extent that the alleged infringement arises from: <br />
                combination, operation, or use of the Software in or with, any technology (including any software, hardware, firmware, system, or network) or service not provided by S39 Global or specified for your use in the Documentation; <br />
                modification of the Software other than: (a) by S39 Global in connection with these Terms; or (b) with S39 Global 's express written authorization and in strict accordance with S39 Global 's written directions and specifications; <br />
                use of any version of the Software other than the most current version or failure to timely implement any Maintenance Release, modification, update, or replacement of the Software made available to you by S39 Global; <br />
                use of the Software after S39 Global 's notice to you of such activity's alleged or actual infringement, misappropriation, or other violation of a third party's rights; <br />
                negligence, abuse, misapplication, or misuse of the Hardware, the Software or Documentation by or on behalf of you, your representatives, or a third party; <br />
                use of the Hardware, Software or Documentation by or on behalf of you that is outside the purpose, scope, or manner of use authorized by these Terms or in any manner contrary to S39 Global 's instructions; <br />
                events or circumstances outside of S39 Global 's commercially reasonable control (including any third-party hardware, software, or system bugs, defects, or malfunctions); or <br />
                third-party claims or Losses for which you are obligated to indemnify S39 Global pursuant to Section 12.2 . <br />
                Your Indemnification of S39 Global. You agree that you shall indemnify, defend, and hold harmless S39 Global and its affiliates, and each of its and their respective officers, directors, employees, agents, subcontractors, successors and assigns from and against any and all Losses incurred by you resulting from any Action by a third party: <br />
                that any Intellectual Property Rights is or will be infringed, misappropriated, or otherwise violated by any use or combination of the Software and/or Portal by you with any hardware, software, system, network, service, or other matter whatsoever that is neither provided by S39 Global nor authorized by S39 Global under these Terms and the Documentation; and <br />
                relating to facts that, if true, would constitute a breach by you of any representation, warranty, covenant, or obligation under these Terms; <br />
                relating to your negligence, abuse, misapplication, misuse or more culpable act or omission (including recklessness or wilful misconduct) with respect to the Software, Portal, or Documentation or otherwise in connection with these Terms; or <br />
                relating to your use of the Software or Portal that is outside the purpose, scope or manner of use authorized by these Terms or the Documentation, or in any manner contrary to S39 Global 's instructions. <br />
                Indemnification Procedures. Each party shall promptly notify the other party in writing of any Action for which such party believes it is entitled to be indemnified pursuant to Section 12.1 or Section 12.2. The party seeking indemnification (the " Indemnitee") shall cooperate with the other party (the " Indemnitor") at the Indemnitor's sole cost and expense. The Indemnitor shall promptly assume control of the defence and investigation of such Action and shall employ counsel of its choice to handle and defend the same, at the Indemnitor's sole cost and expense. The Indemnitee may participate in and observe the proceedings at its own cost and expense with counsel of its own choosing. The Indemnitor shall not settle any Action on any terms or in any manner that adversely affects the rights of any Indemnitee without the Indemnitee's prior written consent, which shall not be unreasonably withheld or delayed. The Indemnitee's failure to perform any obligations under this Section 12.3 will not relieve the Indemnitor of its obligations under this Section 12, except to the extent that the Indemnitor can demonstrate that it has been materially prejudiced as a result of such failure. <br />
                Goods Not for Resale or Export. You represent and warrant that you are buying the Hardware and respective Software and Project licenses from the Website for your own personal or household use only, and not for resale or export. You further represent and warrant that all purchases are intended for final delivery to locations outside the Excluded Jurisdictions and will not be provided to any Disqualified Person. <br />
                Term. This agreement shall commence on the day you accept these terms and shall continue for so long as you use the Hardware and/or Software (the " Term"). <br />
                Dispute Resolution. PLEASE READ THIS SECTION CAREFULLY BECAUSE IT IS AN AGREEMENT TO ARBITRATE DISPUTES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF. <br />
                In consideration for our provision of the Products, Hardware, Portal, and Software to you, you and S39 Global each agree that any and all disputes or claims arising under, out of, in connection with, or related to your use of the Product, Hardware, Portal, Software, or these Terms in any fashion, or the subject matter, negotiation, performance, termination, interpretation, or formation of the agreement resulting from your acceptance of these Terms, (a " Dispute") must be resolved exclusively in binding arbitration. However, a party may assert a claim in small claims court, if the asserted claim qualifies and so long as the matter remains in such court and advances only on an individual (non-class, non-representative) basis. These Terms, including the right to Arbitrate, is intended to be broadly interpreted and the Federal Arbitration Act governs the enforcement of these Terms to arbitrate. <br />
                For any Dispute with S39 Global, you agree first to contact us at support@s39global.com and attempt to resolve the Dispute with us informally. In the event that we do not resolve a Dispute informally, we each agree to resolve any Dispute (excluding any claims for injunctive or other equitable relief) arising out of or in connection with or relating to these Terms, or the breach or alleged breach thereof, by binding arbitration by the Judicial Arbitration and Mediation Services (" JAMS") pursuant to its Comprehensive Arbitration Rules and Procedures and shall be conducted in Wyoming, unless otherwise agreed to in writing by the parties. Each party will be responsible for paying any JAMS filing, administrative and arbitrator fees in accordance with JAMS rules. The award rendered by the arbitrator shall include costs of arbitration, reasonable attorneys' fees and reasonable costs for expert and other witnesses, and any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Nothing in this Section shall prevent either party from seeking injunctive or other equitable relief from the courts as necessary to prevent the actual or threatened infringement, misappropriation, or violation of that party's data security, intellectual property rights, or other proprietary rights. <br />

                </p>
                <h3 className='title-color'>No Class Action; No Jury Trial.</h3>
                <p>
                    ALL CLAIMS MUST BE BROUGHT IN THE PARTIES' INDIVIDUAL CAPACITY, AND NO CLASS ACTION OR REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL THEORIES OF LIABILITY OR PRAYERS FOR RELIEF MAY BE MAINTAINED IN ANY ARBITRATION OR OTHER PROCEEDING UNDER THESE TERMS. UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS. YOU AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND WE ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. <br />

                </p>
                <h3 className='title-color'>Miscellaneous</h3>
                <p>    Severability. Every provision of these Terms will be construed, to the extent possible, so as to be valid and enforceable. If any provision of these Terms is construed or held by a court of competent jurisdiction to be invalid, illegal or otherwise unenforceable, such provision will be deemed severed from these Terms, and all other provisions will remain in full force and effect <br />
                Waiver. Our failure at any time to enforce any of the provisions of these Terms or any right or remedy available hereunder or at law or in equity, or to exercise any option herein provided, will not constitute a waiver of such provision, right, remedy or option or in any way affect the validity of these Terms. Our waiver of any default will not be deemed a continuing waiver but will apply solely to the instance to which such waiver is directed. <br />
                Headings; Summaries. The section headings and any plain English summaries appearing in these Terms are inserted only as a matter of convenience and in no way define, limit, construe or describe the scope or extent of such section or in any way affect such section. <br />
                No Assignment. These Terms, and any rights and licenses granted hereunder, may not be transferred, or assigned by you, but may be assigned by us without restriction. Any attempted transfer or assignment in violation hereof shall be null and void. <br />
                No Third-Party Beneficiaries. Other than as expressly provided in these Terms, no third-party beneficiaries are intended or will be construed as created by these Terms. <br />
                Survival. All Sections which by their nature should survive the termination of these Terms shall continue in full force and effect, notwithstanding any termination of these Terms. <br />
                Notices Electronic Communications. S39 Global may provide notifications, whether such notifications are required by law or are for marketing or other business-related purposes through posting of such notice on the Website. You agree that all agreements, notices, disclosures, and other communication we provide to you via the Website to satisfy any legal requirement that such communications be in writing. We reserve the right to determine the form and means of providing notification to our users. <br />
                </p>
            </div>
        </div>
    );
};

export default TermsCondition;